In [1]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [5]:
input_files = [
  'edgar_allan_poe.txt',
  'robert_frost.txt',
]

In [9]:
# collect data into list
# loop through each file ,save each line to a list
input_texts=[]
labels=[]
for lable,f in enumerate(input_files):
    print(f"{f} corresponting to {lable}")
    for line in open(f):
        line=line.rstrip().lower() #rstrip remove the new line notation
        if line:
            # remove puncutaion
            line=line.translate(str.maketrans('','',string.punctuation))
            input_texts.append(line)
            labels.append(lable)


edgar_allan_poe.txt corresponting to 0
robert_frost.txt corresponting to 1


In [11]:
train_text, test_text, Ytrain, Ytest = train_test_split(input_texts, labels)

In [13]:
print(len(train_text))
print(len(test_text))
print(len(Ytrain))
print(len(Ytest))

1618
540
1618
540


In [19]:
print(train_text[:5])
print(test_text[:5])

['to make it surer that i was a witch', 'hath little of earth in it', 'for we knew not the month was october', 'charge that to upstart inexperience', 'to breathe the incense of those slumbering roses']
['of yawning lenses', 'to ridgely torrence', 'a single leaf was on a bough', 'but the skies that angel trod', 'resignedly beneath the sky']


In [18]:
print(Ytrain[:5])
print(Ytest[:5])

[1, 0, 0, 1, 0]
[1, 1, 1, 0, 0]


In [25]:
# creating a mapping from unique words to unique integes index
idx=1
word2idx = {'<unk>': 0}
for text in train_text:
    tokens=text.split()
    for token in tokens:
        if token not in word2idx:
            word2idx[token]=idx
            idx+=1


In [27]:
print(word2idx)
# here unk is just for make indexing for one bcs we have multiplicaiton ahead

{'<unk>': 0, 'to': 1, 'make': 2, 'it': 3, 'surer': 4, 'that': 5, 'i': 6, 'was': 7, 'a': 8, 'witch': 9, 'hath': 10, 'little': 11, 'of': 12, 'earth': 13, 'in': 14, 'for': 15, 'we': 16, 'knew': 17, 'not': 18, 'the': 19, 'month': 20, 'october': 21, 'charge': 22, 'upstart': 23, 'inexperience': 24, 'breathe': 25, 'incense': 26, 'those': 27, 'slumbering': 28, 'roses': 29, 'both': 30, 'us': 31, 'but': 32, 'look': 33, 'how': 34, 'turns': 35, 'out': 36, 'youthful': 37, 'forms': 38, 'and': 39, 'faces': 40, 'hold': 41, 'door': 42, 'bones': 43, 'didnt': 44, 'try': 45, 'tell': 46, 'me': 47, 'whether': 48, 'as': 49, 'can': 50, 'fall': 51, 'keep': 52, 'abouncing': 53, 'on': 54, 'our': 55, 'feet': 56, 'speculation': 57, 'never': 58, 'could': 59, 'have': 60, 'done': 61, 'thing': 62, 'did': 63, 'takes': 64, 'moon': 65, 'this': 66, 'suns': 67, 'wizard': 68, 'so': 69, 'eden': 70, 'sank': 71, 'grief': 72, 'is': 73, 'my': 74, 'sincere': 75, 'reply': 76, 'you': 77, 'will': 78, 'be': 79, 'likely': 80, 'regard'

In [28]:
len(word2idx )

2539

In [30]:
# conver all data into integer formate
# create each line of word into integer list

train_text_int=[]
test_text_int=[]

for text in train_text:
    tokens=text.split() 
    line_as_int=[word2idx[token] for token in tokens ]
    train_text_int.append(line_as_int)


for text in test_text:
    tokens=text.split()
    line_as_int=[word2idx.get(token,0)for token in tokens]
    test_text_int.append(line_as_int)


In [33]:
print("int list of each line train",train_text_int[100:115])
print("int list of each line test ",test_text_int[100:115])

int list of each line train [[14, 385, 208, 386, 387, 14, 8, 388], [3, 389, 49, 172, 390, 391, 12, 19, 392], [39, 393, 3, 191, 8, 394, 395], [396, 125, 397], [398, 5, 399], [6, 60, 400, 93, 19, 401, 402, 403], [207, 226, 404, 93, 66, 73, 19, 405, 12, 3], [34, 406, 8, 407, 145, 408], [14, 19, 409, 410, 12, 19, 411], [412, 6, 165, 137, 3, 413, 79, 414, 100], [77, 130, 77, 165, 137, 229, 131, 73], [415, 416, 83, 19, 392], [172, 19, 417, 418, 419, 226, 420, 14, 47], [421, 54, 19, 422, 40, 12, 19, 29], [286, 3, 423, 424, 39, 425, 36, 207, 426]]
int list of each line test  [[39, 0, 0], [77, 167, 55, 0, 300, 102, 84, 1956], [1971, 0, 0, 19, 0, 12, 429, 450], [830, 917, 306, 168, 1923, 1, 0, 39, 43], [0, 6, 413, 79, 1, 60, 107, 2467, 0], [548, 16, 58, 59, 309, 36, 655, 43, 103, 125], [556, 18, 343, 107, 87, 1100], [77, 625, 782, 1892, 1892, 1892, 1892, 755], [19, 0, 0, 0, 1192, 84, 139, 344], [103, 987, 1, 1369], [32, 6, 0, 222, 7, 902, 226, 0], [189, 390, 1744, 596, 796], [930, 6, 105], [706,

In [34]:
# initialize A and pi matrices - for both classes
V = len(word2idx) #total no of vector or words is equvalant to M in theory

A0 = np.ones((V, V)) #matrix of  A term probality of state transiton term
pi0 = np.ones(V) #list of propablity of first term

A1 = np.ones((V, V))
pi1 = np.ones(V)

In [35]:
# now mathematical calculation for A and Pi
# here one thing imp that data we pass in is only for single class at a time
def compute_counts(test_text_int,A,Pi):
    for tokens in test_text_int:
        last_idx=None
        for idx in tokens:
            if last_idx is None:
                # this is first word in sentence
                Pi[idx]+=1
            else:
                # last word exist so count the word
                A[last_idx,idx]+=1
                # update the last index
                last_idx=idx

# in 1st case we want value from the first class which is class 0 and papulate them to A and pi
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0) 
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 1], A1, pi1)

In [37]:
print(A0)
print(pi0)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
[ 1. 56.  1. ...  1.  1.  2.]


In [38]:
# normalize A and pi so they are valid probability matrices
# convince yourself that this is equivalent to the formulas shown before
A0 /= A0.sum(axis=1, keepdims=True) #keepdims mean keep the same dimention intact
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [40]:
# log A and pi since we don't need the actual probs
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [42]:
# compute priors
count0 = sum(y == 0 for y in Ytrain)
count1 = sum(y == 1 for y in Ytrain)
total = len(Ytrain)
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0, p1

(0.34177997527812115, 0.6582200247218789)

In [43]:
# build a classifier
class Classifier:
  def __init__(self, logAs, logpis, logpriors):
    self.logAs = logAs
    self.logpis = logpis
    self.logpriors = logpriors
    self.K = len(logpriors) # number of classes

  def _compute_log_likelihood(self, input_, class_):
    logA = self.logAs[class_]
    logpi = self.logpis[class_]

    last_idx = None
    logprob = 0
    for idx in input_:
      if last_idx is None:
        # it's the first token
        logprob += logpi[idx]
      else:
        logprob += logA[last_idx, idx]
      
      # update last_idx
      last_idx = idx
    
    return logprob
  
  def predict(self, inputs):
    predictions = np.zeros(len(inputs))
    for i, input_ in enumerate(inputs):
      posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] \
             for c in range(self.K)]
      pred = np.argmax(posteriors)
      predictions[i] = pred
    return predictions

In [44]:
# each array must be in order since classes are assumed to index these lists
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [45]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == Ytrain)}")

Train acc: 0.7317676143386898


In [46]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == Ytest)}")

Test acc: 0.7203703703703703


In [47]:
from sklearn.metrics import confusion_matrix, f1_score


In [48]:
cm = confusion_matrix(Ytrain, Ptrain)
cm

array([[ 140,  413],
       [  21, 1044]], dtype=int64)

In [49]:
f1_score(Ytrain, Ptrain)

0.8279143536875496

In [50]:
f1_score(Ytest, Ptest)

0.8254335260115606