In [4]:
from sklearn.feature_extraction.text import CountVectorizer


In [7]:
# define the corpus:- collection of writing
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [8]:
vectorizer=CountVectorizer()

In [9]:
x=vectorizer.fit_transform(corpus)

In [10]:
# it gives the feature that are unique as well more than one
vectorizer.get_feature_names_out()


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [14]:
# here the number of count of feature in x and corpus on y asix 
import numpy as np
from scipy.sparse import csr_matrix
csr_matrix(x, dtype=np.int8).toarray()
# x.toarray

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int8)

In [30]:
vectorizer2=CountVectorizer(analyzer='word',ngram_range=(1,2))  #here we can give range 
x2=vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['and', 'and this', 'document', 'document is', 'first',
       'first document', 'is', 'is the', 'is this', 'one', 'second',
       'second document', 'the', 'the first', 'the second', 'the third',
       'third', 'third one', 'this', 'this document', 'this is',
       'this the'], dtype=object)

In [31]:
csr_matrix(x2, dtype=np.int8).toarray()

array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1]],
      dtype=int8)

In [28]:
vectorizer3=CountVectorizer(analyzer='word',ngram_range=(2,2))  #here we can give range 
x3=vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [29]:
csr_matrix(x3, dtype=np.int8).toarray()

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [47]:
vectorizer4=CountVectorizer()
tokenzer=vectorizer.build_tokenizer()
corpus1="hello how are you,some thing " " fissy going on"
tokenzer(corpus1)
# it split words
# print(corpus1.split())

['hello', 'how', 'are', 'you', 'some', 'thing', 'fissy', 'going', 'on']

In [45]:
corpus1.split()

['hello', 'how', 'are', 'you,some', 'thing', 'fissy', 'going', 'on']