In [10]:
from sklearn.feature_extraction.text import CountVectorizer


In [11]:
# define the corpus:- collection of writing
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

In [12]:
vectorizer=CountVectorizer()

In [13]:
x=vectorizer.fit_transform(corpus)

In [14]:
# it gives the feature that are unique as well more than one
vectorizer.get_feature_names_out()


array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [15]:
# here the number of count of feature in x and corpus on y asix 
import numpy as np
from scipy.sparse import csr_matrix
csr_matrix(x, dtype=np.int8).toarray()
# x.toarray

array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int8)

In [16]:
vectorizer2=CountVectorizer(analyzer='word',ngram_range=(1,2))  #here we can give range 
x2=vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

array(['and', 'and this', 'document', 'document is', 'first',
       'first document', 'is', 'is the', 'is this', 'one', 'second',
       'second document', 'the', 'the first', 'the second', 'the third',
       'third', 'third one', 'this', 'this document', 'this is',
       'this the'], dtype=object)

In [17]:
csr_matrix(x2, dtype=np.int8).toarray()

array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1]],
      dtype=int8)

In [18]:
vectorizer3=CountVectorizer(analyzer='word',ngram_range=(2,2))  #here we can give range 
x3=vectorizer3.fit_transform(corpus)
vectorizer3.get_feature_names_out()

array(['and this', 'document is', 'first document', 'is the', 'is this',
       'second document', 'the first', 'the second', 'the third',
       'third one', 'this document', 'this is', 'this the'], dtype=object)

In [19]:
csr_matrix(x3, dtype=np.int8).toarray()

array([[0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [20]:
vectorizer4=CountVectorizer()
tokenzer=vectorizer.build_tokenizer()
corpus1="hello how are you,some thing " " fissy going on"
tokenzer(corpus1)
# it split words
# print(corpus1.split())

['hello', 'how', 'are', 'you', 'some', 'thing', 'fissy', 'going', 'on']

In [21]:
corpus1.split()

['hello', 'how', 'are', 'you,some', 'thing', 'fissy', 'going', 'on']

In [22]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

import nltk
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.corpus import wordnet

In [23]:
nltk.download("wordnet")
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ashut\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ashut\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ashut\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ashut\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [24]:
df=pd.read_csv("bbc_text_cls.csv")
df.head()

text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [35]:
len(df)
input=df['text']
labels=df['labels']

In [36]:
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
# plt.hist(labels)
# plt.show()


In [38]:
# labels.hist(figsize=(10, 5));

In [39]:
from sklearn.model_selection import train_test_split
inputs_train, inputs_test, Ytrain, Ytest = train_test_split(
    input, labels, random_state=123)


In [46]:
vectorizer=CountVectorizer()

In [47]:
Xtrain=vectorizer.fit_transform(inputs_train) #we fit_trans 
Xtest=vectorizer.transform(inputs_test)# we not use fit_tans bcs test sample can be of other type

In [48]:
Xtrain

<1668x26287 sparse matrix of type '<class 'numpy.int64'>'
	with 337411 stored elements in Compressed Sparse Row format>

In [49]:
# it show the sparsh matrix
csr_matrix(Xtrain, dtype=np.int8).toarray()

array([[0, 3, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)

In [50]:
(Xtrain!=0).sum()/np.prod(Xtrain.shape)

0.007695239935415004

model=MultinomialNB()
model.fit(Xtrain,Ytrain)

In [52]:
# this is naiv beyar algo work on probablity used mainly in nlp 
model=MultinomialNB()
model.fit(Xtrain,Ytrain)

MultinomialNB()

In [54]:
print("train score",model.score(Xtrain,Ytrain))
print("test score",model.score(Xtest,Ytest))

train score 0.9922062350119905
test score 0.9712746858168761


In [57]:
# with stop words
vectorizer=CountVectorizer(stop_words='english')
Xtrain=vectorizer.fit_transform(inputs_train)
Xtest=vectorizer.transform(inputs_test)
model1=MultinomialNB()
model1.fit(Xtrain,Ytrain)
print("train score",model1.score(Xtrain,Ytrain))
print("test score",model1.score(Xtest,Ytest))

train score 0.9928057553956835
test score 0.9766606822262118


In [59]:
def get_wordnet_pos(treebank_tag):
  if treebank_tag.startswith('J'):
    return wordnet.ADJ
  elif treebank_tag.startswith('V'):
    return wordnet.VERB
  elif treebank_tag.startswith('N'):
    return wordnet.NOUN
  elif treebank_tag.startswith('R'):
    return wordnet.ADV
  else:
    return wordnet.NOUN
class LemmaTokenizer:
  def __init__(self):
    self.wnl = WordNetLemmatizer()
  def __call__(self, doc):
    tokens = word_tokenize(doc)
    words_and_tags = nltk.pos_tag(tokens)
    return [self.wnl.lemmatize(word, pos=get_wordnet_pos(tag)) \
            for word, tag in words_and_tags]

In [61]:
# usign lametization
vectorizer=CountVectorizer(tokenizer=LemmaTokenizer())
Xtrain=vectorizer.fit_transform(inputs_train)
Xtest=vectorizer.transform(inputs_test)
model1=MultinomialNB()
model1.fit(Xtrain,Ytrain)
print("train score",model1.score(Xtrain,Ytrain))
print("test score",model1.score(Xtest,Ytest))

c:\Users\ashut\Desktop\myNLP\myNLP_venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


train score 0.9922062350119905
test score 0.9676840215439856


In [62]:
# stem tokenizer
class StemTokenizer:
  def __init__(self):
    self.porter = PorterStemmer()
  def __call__(self, doc):
    tokens = word_tokenize(doc)
    return [self.porter.stem(t) for t in tokens]

In [63]:
# using stemming 
vectorizer=CountVectorizer(tokenizer=StemTokenizer())
Xtrain=vectorizer.fit_transform(inputs_train)
Xtest=vectorizer.transform(inputs_test)
model1=MultinomialNB()
model1.fit(Xtrain,Ytrain)
print("train score",model1.score(Xtrain,Ytrain))
print("test score",model1.score(Xtest,Ytest))

c:\Users\ashut\Desktop\myNLP\myNLP_venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


train score 0.9892086330935251
test score 0.9694793536804309


In [67]:
# now simple spliting 
def simple_tokenizer(s):
  return s.split()


In [71]:
vectorizer=CountVectorizer(tokenizer=simple_tokenizer)
Xtrain=vectorizer.fit_transform(inputs_train)
Xtest=vectorizer.transform(inputs_test)
model=MultinomialNB()
model.fit(Xtrain,Ytrain)
print("train score",model.score(Xtrain,Ytrain))
print("test score",model.score(Xtest,Ytest))


c:\Users\ashut\Desktop\myNLP\myNLP_venv\Lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


train score 0.9952038369304557
test score 0.9712746858168761
